<BudgetScreen>:
    name: root.titre_page
    titre: "Mon Budget"
    sous_titre: "Analyse des dépenses"

    orientation : "vertical"

    Header:
        title: "Mon budget"
        subtitle: "Analyse des dépenses mensuelles"

    MDScrollView:
        do_scroll_x : False

        # Conteneur des cartes à l'intérieur du ScrollView
        MDBoxLayout:        # Ce MDBoxLayout contient toutes les cartes de notre structure scrollable.
            orientation: "vertical"
            #size_hint_y: None       # CRITIQUE pour les ScrollView : Le conteneur doit avoir une hauteurnon proportionnelle pour que le ScrollView puisse la calculer.
            #height: self.minimum_height         # CRITIQUE : La hauteur est ajustée automatiquement pour correspondre à la somme minimale de la hauteur de tous ses enfants (cartes).
            adaptive_height: True
            padding: dp(16)         # Espace de 16 dp tout autour du contenu.
            spacing: dp(16)         # Espace de 16 dp entre chaque élément enfant (entre les cartes).

            # --- CARTE PRINCIPALE : Suivi du budget ---
            MDCard:         # Un conteneur qui affiche un élément Material Design élevé (avec ombre).
                size_hint: 1, None      # Prend 100% de la largeur (1) et une hauteur fixe (None).
                height: dp(280)         # Hauteur fixe de la carte principale.
                padding: dp(18)         # Espace intérieur dans la carte.
                orientation: "vertical" # Les éléments à l'intérieur de la carte sont empilés verticalement.
                radius: [12]            # Définit le rayon des coins arrondis à 12 dp.
                elevation: 0.5          # Niveau d'ombre de la carte.
                md_bg_color: app.custom_colors[app.theme_cls.theme_style]["bg_primary"] # colore toute notre carte en blanc
                spacing: dp(5) #ajoute de l'espace entre les éléments

                # Le MDLabel "Budget mensuel"
                MDLabel:
                    text: "Budget mensuel"

                Widget: # espace entre titre et montant
                    size_hint_y: None
                    height: dp(6)

                # Le MDLabel du montant (Budget Total)
                MDLabel:
                    text: str(int(root.budget_total)) + " FC"
                    font_style: "H5"
                    theme_text_color: "Primary"

                Widget: # pour ajouter l'espace entre le montant et le pourcentage
                    size_hint_y: None
                    height: dp(15)

                # Montant utilisé
                MDBoxLayout:
                    size_hint_y: None
                    height: dp(15)

                    MDLabel:
                        text: "Dépenses actuelles"
                        theme_text_color: "Secondary"

                    MDLabel:
                        text: str(int(root.montant_utilise)) + " FC"
                        halign: "right"
                        theme_text_color: "Custom"
                        text_color: 1, 0.3, 0.3, 1  # Rouge doux
                
                Widget: # espace entre dépenses et progress bar
                    size_hint_y: None
                    height: dp(10)

                # Barre de progression
                MDProgressBar:
                    value: root.pourcentage_utilise
                    color: app.custom_colors[app.theme_cls.theme_style]["accent"]
                    size_hint_x: 1
                    height: dp(4)
                    radius: [4]
                    spacing: dp(2)

                # Pourcentage
                MDLabel:
                    text: str(root.pourcentage_utilise) + "% consommé"
                    font_style: "Caption"
                    theme_text_color: "Secondary"

                Widget:
                    size_hint_y: None
                    height: dp(10)

                # Le montant restant (Grosse taille)
                MDBoxLayout:
                    size_hint_y: None
                    height: dp(50)

                    MDLabel:
                        text: "Reste à dépenser"
                        font_style: "Subtitle1"
                        theme_text_color: "Primary"
                        

                    MDLabel: 
                        text: str(int(root.montant_restant)) + " FC"
                        halign: "right"
                        font_style: "H6"  # Même taille que le budget total
                        theme_text_color: "Custom"
                        text_color: 0.1, 0.5, 0.8, 1 #Couleur bleue

                # Bouton "Modifier le budget"
                MDFillRoundFlatIconButton:

                    text: "Modifier le budget"
                    icon : "note-edit-outline"

                    size_hint_x: 1
                    #radius: [2, 2, 2, 2]
                    height: dp(48)
                    #icon_size: "24dp"

                    md_bg_color: app.custom_colors[app.theme_cls.theme_style]["accent"]
                    text_color: 1, 1, 1, 1
                    elevation : 0.5

                    on_release: root.modifier_budget()


            # --- STATISTIQUES SECONDAIRES côte à côte ---
            MDGridLayout:
                cols: 2
                spacing: dp(12)
                adaptive_height: True

                MDCard:
                    padding: dp(12)
                    size_hint: 1, None
                    height: dp(100)
                    elevation: 0.5
                    md_bg_color: app.custom_colors[app.theme_cls.theme_style]["bg_primary"]
                    

                    MDBoxLayout:
                        orientation: "vertical"

                        MDLabel:
                            text: "Dépenses journalières"
                            font_style: "Caption"
                            #font_size: dp(15)

                        Widget: # espace entre titre et montant
                            size_hint_y: None
                            height: dp(6)

                        MDLabel:
                            text: str(int(root.depenses_journalieres))
                            font_style: "H5"
                            #theme_text_color: "Custom"
                            #text_color: 0.2, 0.2, 0.2, 1
                        
                        MDLabel:
                            text: "FC / jour"
                            font_style : "Caption"

                # Seconde carte de statistique : Jours restants
                MDCard:
                    padding: dp(12)
                    size_hint: 1, None
                    height: dp(100)
                    elevation: 0.5
                    md_bg_color: app.custom_colors[app.theme_cls.theme_style]["bg_primary"]


                    MDBoxLayout:
                        orientation: "vertical"
                        MDLabel:
                            text: "Jours restants"
                            font_style : "Caption"

                        MDLabel:
                            text: str(root.jours_restants) 
                            font_style: "H5"
                            #theme_text_color: "Custom"
                            #text_color: 0.2, 0.2, 0.2, 1
                        
                        MDLabel:
                            text: "Jours"
                            font_style : "Caption"
                            
