<StatCard>:
    orientation: 'vertical'
    padding: dp(10)
    spacing: dp(5)
    MDLabel:
        text: root.titre
        font_style: "Subtitle2"                    # ['H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'Subtitle1', 'Subtitle2', 'Body1', 'Body2', 'Button', 'Caption', 'Overline', 'Icon']
        halign: "left"
    MDLabel:
        text: root.montant
        theme_text_color: "Custom"
        text_color: root.couleur_texte
        font_style: "H6"
        halign: "left"
        bold: True

    MDLabel:
        text: 'FC'
        theme_text_color: "Secondary"
#        text_color: root.couleur_texte
        font_style: "Subtitle2"



<ItemCategorie@MDBoxLayout>:
    nom: ""
    montant: ""
    icone: "circle"
    couleur_icone: 1, 1, 1, 1
    orientation: 'horizontal'
    adaptive_height: True
    spacing: dp(15)
    padding: [dp(5), dp(10)]

    MDIcon:
        icon: root.icone
        theme_text_color: "Secondary"
        #theme_text_color: "Custom"
        #text_color: root.couleur_icone
        pos_hint: {"center_y": .5}
        font_size: "20sp"

    MDLabel:
        text: root.nom
        theme_text_color: "Secondary"
        halign: "left"
        font_style: "Subtitle2"
        pos_hint: {"center_y": .5}

    MDLabel:
        text: root.montant
        halign: "right"
        bold: True
        font_style: "Subtitle2"
        pos_hint: {"center_y": .5}



<GraphiqueBarres>:
    orientation: 'vertical'
    padding: dp(10)

    # Zone des axes et des barres
    MDBoxLayout:
        size_hint_y: 0.8
        canvas.before:
            Color:
                rgba: 0.9, 0.9, 0.9, 1  # Couleur des lignes de grille
            # Lignes horizontales de repère (0, 15k, 30k, 60k)
            Line:
                points: [self.x + dp(30), self.y + dp(20), self.right, self.y + dp(20)]
            Line:
                points: [self.x + dp(30), self.y + dp(70), self.right, self.y + dp(70)]
            Line:
                points: [self.x + dp(30), self.y + dp(120), self.right, self.y + dp(120)]


        # Dessin manuel des barres pour Janvier, Février et Mars
        Widget:
            canvas:
                # JANVIER
                Color:
                    rgba: 0.1, 0.7, 0.3, 1 # Vert Revenus
                Rectangle:
                    pos: [self.x + dp(40), self.y + dp(20)]
                    size: [dp(20), dp(100)] # Hauteur simulée
                Color:
                    rgba: 1, 0.3, 0.5, 1 # Rose Dépenses
                Rectangle:
                    pos: [self.x + dp(65), self.y + dp(20)]
                    size: [dp(20), dp(40)]

                # FÉVRIER
                Color:
                    rgba: 0.1, 0.7, 0.3, 1
                Rectangle:
                    pos: [self.x + dp(120), self.y + dp(20)]
                    size: [dp(20), dp(90)]
                Color:
                    rgba: 1, 0.3, 0.5, 1
                Rectangle:
                    pos: [self.x + dp(145), self.y + dp(20)]
                    size: [dp(20), dp(60)]

                # MARS
                Color:
                    rgba: 0.1, 0.7, 0.3, 1
                Rectangle:
                    pos: [self.x + dp(200), self.y + dp(20)]
                    size: [dp(20), dp(110)]
                Color:
                    rgba: 1, 0.3, 0.5, 1
                Rectangle:
                    pos: [self.x + dp(225), self.y + dp(20)]
                    size: [dp(20), dp(50)]

    # Étiquettes des mois (Jan, Fév, Mar)
    MDBoxLayout:
        size_hint_y: 0.1
        padding: [dp(40), 0, 0, 0]
        MDLabel:
            text: "Jan"
            font_style: "Caption"
        MDLabel:
            text: "Fév"
            font_style: "Caption"
        MDLabel:
            text: "Mar"
            font_style: "Caption"

    # Légende (Revenus / Dépenses)
    MDBoxLayout:
        size_hint_y: 0.1
        spacing: dp(10)
        padding: [dp(40), 0, 0, 0]

        MDBoxLayout:
            #adaptive_width: True
            orientation: 'horizontal'
            spacing: dp(15)
            MDIcon:
                icon: "checkbox-blank"
                theme_text_color: "Custom"
                text_color: 0.1, 0.7, 0.3, 1
                font_size: "14sp"
                adaptive_height: True

            MDLabel:
                text: "Revenus"
                font_style: "Caption"
                theme_text_color: "Custom"
                text_color: 0.1, 0.7, 0.3, 1
                adaptive_height: True

        MDBoxLayout:
            #adaptive_width: True
            orientation: 'horizontal'
            spacing: dp(15)

            MDIcon:
                icon: "checkbox-blank"
                theme_text_color: "Custom"
                text_color: 1, 0.3, 0.5, 1
                font_size: "14sp"
                adaptive_height: True
            MDLabel:
                text: "Dépenses"
                font_style: "Caption"
                theme_text_color: "Custom"
                text_color: 1, 0.3, 0.5, 1
                adaptive_height: True





# ECRAN PRINCIPAL
<DashboardScreen>:
    # Conteneur de la page
    MDBoxLayout:
        orientation: 'vertical'
        size_hint_y: 1

        # EN-TÊTE
        Header:
            title: 'MonBudget'
            subtitle: 'Bienvenu'

        # Conteneur pour le contenu principale (Statistiques)
        MDFloatLayout:
            size_hint_y: 1

            MDScrollView:
                do_scroll_x: False
                MDBoxLayout:
                    orientation: 'vertical'
                    adaptive_height: True
                    padding: dp(10)
                    spacing: dp(10)

                    # 1. CARTE SOLDE DU MOIS
                    MDCard:
                        orientation: 'vertical'
                        size_hint_y: None
                        height: dp(100)
                        radius: dp(0)
                        padding: dp(10)
                        elevation: 0

                        MDLabel:
                            text: "Solde du mois"
                            halign: "left"
                        MDLabel:
                            text: "25 000 FC"
                            font_style: "H4"
                            halign: "left"
                            theme_text_color: "Primary"
                            #bold: True

                    # 2. CARTES REVENUS ET DÉPENSES (Total)
                    MDBoxLayout:
                        adaptive_height: True
                        spacing: dp(15)

                        # Dépenses
                        MDCard:
                            adaptive_height: True
                            radius: dp(15)
                            StatCard:
                                titre: "Dépenses"
                                montant: "-18 000"
                                couleur_texte: 1, 0.3, 0.3, 1 # Rose/Rouge

                        # Revenus
                        MDCard:
                            radius: dp(0)
                            adaptive_height: True
                            StatCard:
                                titre: "Revenus"
                                montant: "+43 000"
                                couleur_texte: 0.1, 0.7, 0.3, 1 # Vert

                    # 3. DÉPENSES PAR CATÉGORIE
                    MDBoxLayout:
                        adaptive_height: True
                        #spacing: dp(15)

                        MDCard:
                            orientation: 'vertical'
                            adaptive_height: True
                            padding: dp(15)
                            spacing: dp(15)
                            radius: dp(15)
                            elevation: 0

                            MDLabel:
                                text: "Dépenses par catégorie"
                                adaptive_height: True

                            # Graphique Circulaire (Canvas)
                            MDBoxLayout:
                                size_hint: None, None
                                size: dp(140), dp(140)
                                pos_hint: {"center_x": .5}

                                canvas:
                                    Color:
                                        rgba: 1, 0.4, 0.5, 1
                                    Ellipse:
                                        pos: self.pos
                                        size: self.size
                                        angle_start: 0
                                        angle_end: 140
                                    Color:
                                        rgba: 0.2, 0.6, 0.9, 1
                                    Ellipse:
                                        pos: self.pos
                                        size: self.size
                                        angle_start: 140
                                        angle_end: 230
                                    Color:
                                        rgba: 1, 0.8, 0.4, 1
                                    Ellipse:
                                        pos: self.pos
                                        size: self.size
                                        angle_start: 230
                                        angle_end: 300
                                    Color:
                                        rgba: 0.3, 0.8, 0.7, 1
                                    Ellipse:
                                        pos: self.pos
                                        size: self.size
                                        angle_start: 300
                                        angle_end: 360

                            # Liste des items
                            MDBoxLayout:
                                orientation: 'vertical'
                                adaptive_height: True

                                ItemCategorie:
                                    nom: "Alimentation"
                                    montant: "8 000 FC"
                                    icone: "food-apple"
                                    couleur_icone: 1, 0.4, 0.5, 1

                                ItemCategorie:
                                    nom: "Transport"
                                    montant: "5 000 FC"
                                    icone: "car"
                                    couleur_icone: 0.2, 0.6, 0.9, 1

                                ItemCategorie:
                                    nom: "Logement"
                                    montant: "3 000 FC"
                                    icone: "home"
                                    couleur_icone: 1, 0.8, 0.4, 1

                                ItemCategorie:
                                    nom: "Loisirs"
                                    montant: "2 000 FC"
                                    icone: "controller-classic"
                                    couleur_icone: 0.3, 0.8, 0.7, 1

                    # 4. ZONE GRAPHIQUE : Revenus VS Dépenses
                    MDBoxLayout:
                        adaptive_height: True
                        #spacing: dp(15)

                        MDCard:
                            orientation: 'vertical'
                            size_hint_y: None
                            height: dp(250)
                            radius: dp(15)
                            padding: dp(15)

                            MDLabel:
                                text: "Revenus vs Dépenses"
                                bold: True
                                adaptive_height: True

                            GraphiqueBarres:
